baseURL: 'https://starter-hugo-debug-site.netlify.com/'
languageCode: en-us
title: Debug
disableKinds:
  - taxonomy
  - taxonomyTerm

module:
  imports:
  - path: github.com/regisphilibert/hugo-6730--module